### ISSUE TITLE
Layout is broken on linux (tested on firefox and chromium)

### ISSUE THREAD

**Issue by glauberramos** [glauberramos/firedeaz#19]
The layout is currently broken, the columns are not displaying very well

**Comment by glauberramos** [comment]
this issue looks like is fixed now, need someone with linux machine to test again

**Comment by eduaquiles** [comment]
Looks ok on Chrome/FF

![image](https://cloud.githubusercontent.com/assets/354035/9396266/ff68abfe-4769-11e5-96c9-47f0dbd51e21.png)

**Comment by glauberramos** [comment]
Fixed
