### ISSUE TITLE
Login using facebook / google

### ISSUE THREAD

**Issue by glauberramos** [glauberramos/firedeaz#9]

**Comment by glauberramos** [comment]
Dicided to don't have login on the MVP, I am going to follow a similar idea like appear.in

**Comment by yuki24** [comment]
Has this ever been implemented? We'd like to deploy funretro but with an authentication layer and I wasn't sure [the `logUser` function does it](logUser) because email/password is literally hard-coded.

**Comment by glauberramos** [comment]
@yuki24 it is not implemented. email/password is just for security reason when creating a board, it just works for the internal app as you said. I am building a new version that will contain auth, but it will be a paid version. Maybe in the future I can release a free version with login.

**Comment by yuki24** [comment]
@Glauberamos thanks for your super quick reply! I'm very much looking forward to the new version 😀
